---
- name: Install java
  yum:
    name: java-1.8.0-openjdk-devel
    state: present

- name: Get Artifact from Artifactory
  get_url: 
    url: '{{ artifactory_url }}'
    dest: '{{ artifact_path }}'
    username: '{{ repository_login }}'
    password: '{{ repository_pass }}'

- name: Install petclinic systemd init file
  become: yes
  template: src=petclinic.service.j2 dest=/etc/systemd/system/petclinic.service

- name: Start petclinic.service
  systemd:
    state: started
    name: petclinic.service
    daemon_reload: yes